RecipeMPin/RecipeMPin/urls.py
"""
Definition of urls for RecipeMPin.
"""

from datetime import datetime

import app.forms
import app.views
import django.contrib.auth.views
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    # Examples:
    url(r'^$', app.views.home, name='home'),
    url(r'^contact$', app.views.contact, name='contact'),
    url(r'^about', app.views.about, name='about'),
    url(r'^loginpin$', app.views.loginpin, name='loginpin'),
    url(r'^register$', app.views.register, name='register'),
    url(r'^login/$',
        django.contrib.auth.views.login,
        {
            'template_name': 'app/login.html',
            'authentication_form': app.forms.BootstrapAuthenticationForm,
            'extra_context':
                {
                    'title': 'Log in',
                    'year': datetime.now().year,
                }
        },
        name='login'),
    url(r'^logout$',
        django.contrib.auth.views.logout,
        {
            'next_page': '/',
        },
        name='logout'),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
]

RecipeMPin/app/models.py
"""
Definition of models.
"""

from django.contrib.auth.models import User
from django.contrib.auth.models import models


# Create your models here.
class TwoStep(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    pin = models.IntegerField()

RecipeMPin/app/forms.py
"""
Definition of forms.
"""

from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _


class BootstrapAuthenticationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'User name'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder': 'Password'}))
    # pin = forms.IntegerField(widget=forms.PasswordInput({
    #     'class': 'form-control',
    #     'placeholder': 'Pin'}))


class Loginpin(forms.Form):
    pin = forms.IntegerField(label=_("Pin"),
                             widget=forms.PasswordInput({
                                 'class': 'form-control',
                                 'placeholder': 'PIN'}))


# class Register(forms.Form):
#     username = forms.CharField(max_length=254,
#                                widget=forms.TextInput({
#                                    'class': 'form-control',
#                                    'placeholder': 'User name'}))
#     password = forms.IntegerField(label=_("Password"),
#                                   widget=forms.PasswordInput({
#                                       'class': 'form-control',
#                                       'placeholder': 'PIN'}))

RecipeMPin/app/views.py
"""
Definition of views.
"""
from datetime import datetime

from app.ecc import autenticate
from app.forms import Loginpin
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpRequest
from django.http import HttpResponseRedirect
from django.shortcuts import render

from RecipeMPin import settings


@login_required
def home(request):
    """Renders the home page."""
    assert isinstance(request, HttpRequest)
    return render(request,
                  'app/index.html',
                  {
                      'title': 'Home Page',
                      'year': datetime.now().year,
                  })


def contact(request):
    """Renders the contact page."""
    assert isinstance(request, HttpRequest)
    return render(request,
                  'app/contact.html',
                  {
                      'title': 'Contact',
                      'message': 'You can contact us at:',
                      'year': datetime.now().year,
                  })


def about(request):
    """Renders the about page."""
    assert isinstance(request, HttpRequest)
    return render(request,
                  'app/about.html',
                  {
                      'title': 'About',
                      'message': 'M-Pin project for the Computer Systems Security class of the Master in Software Engineering at the Mathematics Research Center A.C.',
                      'year': datetime.now().year,
                  })


@login_required
def loginpin(request):
    """Renders the contact page."""
    form_class = Loginpin
    if request.method == 'POST':
        form = form_class(data=request.POST)
        if form.is_valid():
            alpha = int(request.POST.get('pin', ''))
            identity = request.user.get_username()
            user = User.objects.get(username=identity)
            if not autenticate(alpha, identity, user.twostep.pin):
                logout(request)
                return HttpResponseRedirect(settings.LOGIN_URL)
            else:
                return HttpResponseRedirect('/')
    assert isinstance(request, HttpRequest)
    return render(request,
                  'app/loginpin.html',
                  {
                      'form': form_class,
                      'title': 'Login',
                  })


def register(request):
    """Renders the contact page."""
    # form_class = Register
    # if request.method == 'POST':
    #     form = form_class(data=request.POST)
    #     if form.is_valid():
    #         alpha = int(request.POST.get('password', ''))
    #         identity = request.POST.get('username', '')
    #         # ta = TrustedAuthority(alpha)
    # assert isinstance(request, HttpRequest)
    # return render(request,
    #               'app/register.html',
    #               {
    #                   'form': form_class,
    #                   'title': 'Register',
    #               })

RecipeMPin/app/templates/app/about.html
{% extends "app/layout.html" %} {% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>
<h4>{{ alice }}</h4>

<p>
    {% load staticfiles %}
    <center>
        <img src="{% static "app/image/LOGOTIPO_SIN_FONDO-01.png" %}" style="width:500px;height:500px;" />
    </center>
</p>

{% endblock %}

RecipeMPin/app/templates/app/contact.html
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<address>
    Centro de Investigaci&#243;n en Matem&#225;ticas, A.C. (CIMAT)<br/>
    Unidad Zacatecas<br/>

    Avenida Universidad 222,<br/>
    La Loma, 98068, Zacatecas, M&#233;xico<br/>
    <abbr title="Phone">P:</abbr>
    +52 (492) 99 80 300 / +52 (492) 15 64 331
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br/>
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

{% endblock %}

RecipeMPin/app/templates/app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
    /* Remove the navbar's default rounded borders and increase the bottom margin */
    .navbar {
      margin-bottom: 50px;
      border-radius: 0;
    }
    
    /* Remove the jumbotron's default bottom margin */
     .jumbotron {
      margin-bottom: 0;
    }
   
    /* Add a gray background color and some padding to the footer */
    footer {
      background-color: #f2f2f2;
      padding: 25px;
    }




    </style>
</head>
<body>

<div class="jumbotron">
    <div class="container text-center">
        <table>
            <tr>
                <td>
                    {% load staticfiles %}
                    <img src="{% static "app/image/logo_black.png" %}" style="width:128px;height:128px;">
                </td>
                <td width="100%">
                    <h1>Tasty Meals</h1>
                    <p>Tasty, Easy & Happy</p>
                </td>
                <td><br/></td>
            </tr>
        </table>
    </div>
</div>

<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">
                <img src="{% static "app/image/logo_white.png" %}" style="width:36px;height:36px;">
            </a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                <li class="active"><a href="{% url 'home' %}">Home</a></li>
                <li><a href="#">Upload</a></li>
                <li><a href="#">Featured</a></li>
                <li><a href="#">Staff Pick</a></li>
                <li><a href="{% url 'contact' %}">Contact</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-user"></span> Your Account</a></li>
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    <div class="row">
        <div class="col-sm-4">
            <div class="panel panel-primary">
                <div class="panel-heading">Blueberry smoothie</div>
                <div class="panel-body"><img src="{% static "app\image\02_09_BlueberryBreakfastSmoothie_Final-small-landscape-300.jpg" %}" class="img-responsive" style="width:100%" alt="Image">
                </div>
                <div class="panel-footer">A tasty breakfast for a healthy start into the new day.</div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="panel panel-danger">
                <div class="panel-heading">Gnocchi in marinara sauce</div>
                <div class="panel-body"><img src="{% static "app\image\08_11_GnocchiInMarinaraSauceWithBuffaloMozzarella_titlePicture-small-landscape-300.jpg" %}" class="img-responsive" style="width:100%" alt="Image">
                </div>
                <div class="panel-footer">A handful of selected ingredients give this simple dish its outstanding
                    aroma.
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="panel panel-success">
                <div class="panel-heading">Potato dumplings</div>
                <div class="panel-body"><img src="{% static "app\image\17_05_PotatoDumplings_titlePicture-small-landscape-300.jpg" %}" class="img-responsive" style="width:100%" alt="Image">
                </div>
                <div class="panel-footer">These dumplings are a German classic. I like to prepare them as a side dish
                    for Christmas because they can be easily combined with most of the traditional main dishes.
                </div>
            </div>
        </div>
    </div>
</div>
<br>

<div class="container">
    <div class="row">
        <div class="col-sm-4">
            <div class="panel panel-primary">
                <div class="panel-heading">Chai hot chocolate</div>
                <div class="panel-body"><img src="{% static "app\image\38_08_ChaiVeganHotChocolate_final-small-landscape-300.jpg" %}" class="img-responsive" style="width:100%" alt="Image">
                </div>
                <div class="panel-footer">The spice of chai combined with the sweetness of hot cocoa—the perfect winter
                    drink!
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="panel panel-primary">
                <div class="panel-heading">Butterbeer</div>
                <div class="panel-body"><img src="{% static "app\image\38_15_Butterbeer_final-small-landscape-300.jpg" %}" class="img-responsive" style="width:100%" alt="Image">
                </div>
                <div class="panel-footer">A real treat for children and adults alike. Tastes just like the one in the
                    Three Broomsticks, I’d imagine!
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="panel panel-primary">
                <div class="panel-heading">Spiced salmon</div>
                <div class="panel-body"><img src="{% static "app\image\BengaliSalmon_TitlePicture-small-landscape-300.jpg" %}" class="img-responsive" style="width:100%" alt="Image">
                </div>
                <div class="panel-footer">This dish is so fresh with just a tingling of spiciness – absolutely
                    perfect!
                </div>
            </div>
        </div>
    </div>
</div>
<br><br>

<footer class="container-fluid text-center">
    <p>&copy; {{ year }} CIMAT, A.C.  Made with <span class="glyphicon glyphicon-heart" aria-hidden="true"></span> in
        Guadalupe, Zacatecas.</p>
    <form class="form-inline">Get notified when a new recipe comes:
        <input type="email" class="form-control" size="50" placeholder="Email Address">
        <button type="button" class="btn btn-danger">Sign Up</button>
    </form>
</footer>

</body>
</html>

RecipeMPin/app/templates/app/index2.html
{% extends "app/layout.html" %}

{% block content %}

<div class="jumbotron">
    <h1>Django</h1>
    <p class="lead">Django is a free web framework for building great Web sites and Web applications using HTML, CSS and
        JavaScript.</p>
    <p><a href="https://www.djangoproject.com/" class="btn btn-primary btn-large">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            Django gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://www.djangobook.com/en/2.0/index.html">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>The Python Package Index is a repository of software for the Python programming language.</p>
        <p><a class="btn btn-default" href="https://pypi.python.org/pypi">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Microsoft Azure</h2>
        <p>You can easily publish to Microsoft Azure using Python Tools for Visual Studio. Find out how you can host
            your application using a free trial today.</p>
        <p><a class="btn btn-default" href="http://azure.microsoft.com">Learn more &raquo;</a></p>
    </div>
</div>

{% endblock %}

RecipeMPin/app/templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - Tasty Meals</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}"/>
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
</head>

<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="/" class="navbar-brand">Tasty Meals</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'home' %}">Home</a></li>
                <li><a href="{% url 'about' %}">About</a></li>
                <li><a href="{% url 'contact' %}">Contact</a></li>
            </ul>
            {% include 'app/loginpartial.html' %}
        </div>
    </div>
</div>

<div class="container body-content">
    {% block content %}{% endblock %}
    <hr/>
    <footer>
        <p>&copy; {{ year }} CIMAT, A.C.  Made with <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
            in Guadalupe, Zacatecas.</p>
    </footer>
</div>

<script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
<script src="{% static 'app/scripts/bootstrap.js' %}"></script>
<script src="{% static 'app/scripts/respond.js' %}"></script>
{% block scripts %}{% endblock %}

</body>
</html>

RecipeMPin/app/templates/app/login.html
{% extends "app/layout.html" %} {% block content %}

<h2>{{ title }}</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            <form action=".?next={% url 'register' %}" method="post" class="form-horizontal">
                {% csrf_token %}
                <h4>Use a local account to log in.</h4>
                <hr/>
                <div class="form-group">
                    <label for="id_username" class="col-md-2 control-label">User name</label>
                    <div class="col-md-10">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-2 control-label">Password</label>
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="{% url 'loginpin' %}" />
                        <input type="submit" value="Log in" class="btn btn-default" />
                    </div>
                </div>
                {% if form.errors %}
                <p class="validation-summary-errors">Please enter a correct user name and password.</p>
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %} {% block scripts %} {% load staticfiles %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script> {% endblock %}

RecipeMPin/app/templates/app/loginpartial.html
{% if user.is_authenticated %}
<form id="logoutForm" action="/logout" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><span class="navbar-brand">Hello {{ user.username }}!</span></li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
    </ul>

</form>

{% else %}

<ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'login' %}">Log in</a></li>
</ul>

{% endif %}

RecipeMPin/app/templates/app/loginpin.html
{% block content %}

<h2>{{ title }}</h2>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - Tasty Meals</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}"/>
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
    <link rel='stylesheet prefetch' href='https://s3-us-west-2.amazonaws.com/s.cdpn.io/183786/waves.css'>
    {% load staticfiles %}
    <!--<link rel="stylesheet" href="css/style.css">-->
    <link rel="stylesheet" href="{% static 'app/content/style.css' %}"/>
</head>

<body>
<div class="row">
    <div id="PINcode">
        <section id="loginForm">
            <form action='' method='post' name='PINform' id='PINform' autocomplete='off'>
                {% csrf_token %} {{ form }}
                <!--<input id='PINbox' type='password' value='' name='PINbox' disabled/>-->
                <!--<input id='id_pin' type='password' value='' name='PINbox' disabled />-->
                <br/>
                <input type='button' class='PINbutton' name='1' value='1' id='1' onClick=addNumber(this); />
                <input type='button' class='PINbutton' name='2' value='2' id='2' onClick=addNumber(this); />
                <input type='button' class='PINbutton' name='3' value='3' id='3' onClick=addNumber(this); />
                <br>
                <input type='button' class='PINbutton' name='4' value='4' id='4' onClick=addNumber(this); />
                <input type='button' class='PINbutton' name='5' value='5' id='5' onClick=addNumber(this); />
                <input type='button' class='PINbutton' name='6' value='6' id='6' onClick=addNumber(this); />
                <br>
                <input type='button' class='PINbutton' name='7' value='7' id='7' onClick=addNumber(this); />
                <input type='button' class='PINbutton' name='8' value='8' id='8' onClick=addNumber(this); />
                <input type='button' class='PINbutton' name='9' value='9' id='9' onClick=addNumber(this); />
                <br>
                <input type='button' class='PINbutton clear' name='-' value='clear' id='-' onClick=clearForm(this); />
                <input type='button' class='PINbutton' name='0' value='0' id='0' onClick=addNumber(this); />
                <!--<input type='button' class='PINbutton enter' name='+' value='enter' id='+' onClick=submitForm(password); />-->
                <input type="submit" class="PINbutton enter" value="enter"/>
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>
<script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
<script src='http://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js'></script>
<script src='https://s3-us-west-2.amazonaws.com/s.cdpn.io/183786/waves.js'></script>
<script type="text/javascript" src="{% static 'app/scripts/index.js' %}"></script>
</body>

{% endblock %} {% block scripts %}

{% load staticfiles %}

<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script> {% endblock %}

RecipeMPin/app/templates/app/register.html
{% extends "app/layout.html" %} {% block content %}

<h2>{{ title }}</h2>

<head>
    <meta charset="UTF-8">
    <title>PINpad</title>


    <link rel='stylesheet prefetch' href='https://s3-us-west-2.amazonaws.com/s.cdpn.io/183786/waves.css'> {% load staticfiles %}
    <!--<link rel="stylesheet" href="css/style.css">-->
    <link rel="stylesheet" href="{% static 'app/content/style.css' %}" />


</head>

<body>
    <!--<div id="PINcode"></div>-->
    <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
    <script src='http://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js'></script>
    <script src='https://s3-us-west-2.amazonaws.com/s.cdpn.io/183786/waves.js'></script>

    <!--{% load staticfiles %}
<script src="{% static 'app/scripts/index.js' %}"></script>
-->

    <div class="row">
        <div id="PINcode">
            <section id="loginForm">
                <form action='' method='post' name='PINform' id='PINform' autocomplete='off'>
                    {% csrf_token %}
                    {{ form }}
                    <!--<input id='PINbox' type='password' value='' name='PINbox' disabled />
                    <input id='id_password' type='password' value='' name='PINbox' disabled />-->
                    <br/>
                    <input type='button' class='PINbutton' name='1' value='1' id='1' onClick=addNumber(this); />
                    <input type='button' class='PINbutton' name='2' value='2' id='2' onClick=addNumber(this); />
                    <input type='button' class='PINbutton' name='3' value='3' id='3' onClick=addNumber(this); />
                    <br>
                    <input type='button' class='PINbutton' name='4' value='4' id='4' onClick=addNumber(this); />
                    <input type='button' class='PINbutton' name='5' value='5' id='5' onClick=addNumber(this); />
                    <input type='button' class='PINbutton' name='6' value='6' id='6' onClick=addNumber(this); />
                    <br>
                    <input type='button' class='PINbutton' name='7' value='7' id='7' onClick=addNumber(this); />
                    <input type='button' class='PINbutton' name='8' value='8' id='8' onClick=addNumber(this); />
                    <input type='button' class='PINbutton' name='9' value='9' id='9' onClick=addNumber(this); />
                    <br>
                    <input type='button' class='PINbutton clear' name='-' value='clear' id='-' onClick=clearForm(this); />
                    <input type='button' class='PINbutton' name='0' value='0' id='0' onClick=addNumber(this); />
                    <!--<input type='button' class='PINbutton enter' name='+' value='enter' id='+' onClick=submitForm(password); />-->
                    <input type="submit" class="PINbutton enter" value="enter" />
                </form>
            </section>
        </div>
        <div class="col-md-4">
            <section id="socialLoginForm"></section>
        </div>
    </div>
</body>

{% endblock %} {% block scripts %}

<script type="text/javascript">
    function addNumber(e){
        //document.getElementById('PINbox').value = document.getElementById('PINbox').value+element.value;
        var v = $( "#id_password" ).val();  //PINbox
        $( "#id_password" ).val( v + e.value );   //PINbox
    }
    function clearForm(e){
        //document.getElementById('PINbox').value = "";
        $( "#id_password" ).val( "" );   //PINbox
    }
    function submitForm(e) {
        if (e.value == "") {
            alert("Enter a PIN");
        } else {
            alert( "Your PIN has been sent! - " + e.value );
            data = {
            pin: e.value
        }
        /*      
        apiCall( data, function( r ) {
            $( "#logo" ).attr( "src", r.site_logo );
            $( ".title-msg" ).text( r.site_msg );
            accent = r.accent;
            $( ".accent-bg" ).css( "background-color", accent );
        });
        */
        
        //document.getElementById('PINbox').value = "";
        $( "#id_password" ).val( "" );   //PINbox
    };
};
</script> {% load staticfiles %}

<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script> {% endblock %}